[project]
name = "Zap: Lightning Address to BOLT11 Invoice Generator"
version = "0.1.0"
description = "Lightning Address â†’ BOLT11 invoice generator with optional PySide6 GUI."
authors = [
    { name = "Wolf", url="https://github.com/vv01f/lightning-address-invoice-generator" }
    { name = "Velas Commerce", url="https://github.com/Velas-Commerce/lightning-address-invoice-generator" }
]
requires-python = ">=3.10"

dependencies = [
    "requests",
    "bech32",
    "PySide6",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
